spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/passangers
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: bestuser
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB


  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml